// apps/angular/src/bugs/Bug1276Page/bug1276Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1276Page.component.html",
})
export class Bug1276PageComponent {

}
<goa-form-item label="Input">
  <goa-input name="input" width="20ch"></goa-input>
</goa-form-item>

<goa-form-item label="Textarea">
  <goa-textarea name="textarea" width="60ch"></goa-textarea>
</goa-form-item>

// apps/react/src/bugs/Bug1276Page.tsx
import React, { useState, useEffect } from 'react';
import { GoAInput, GoATextarea, GoAFormItem } from "@abgov/react-components";

export default function Bug1276Page(props) {
  return (
    <div>
      {/* Input Field */}
      <GoAFormItem label="Input">
        <GoAInput
          name="input"
          width="20ch"
        />
      </GoAFormItem>

      {/* Textarea Field */}
      <GoAFormItem label="Textarea">
        <GoATextarea
          name="textarea"
          width="60ch"
        />
      </GoAFormItem>
    </div>
  )
}
