// apps/angular/src/bugs/Bug1319Page/bug1319Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1319Page.component.html",
  styleUrls: ['./bug1319Page.component.css'],

})
export class Bug1319PageComponent {
  onChange(event: Event) {
    // handle change
    console.log((event as CustomEvent).detail.value);
  }
}

<div class="full-width">
<goa-form-item label="Basic dropdown">
  <goa-dropdown name="item" value="" (_change)="onChange($event)" width="100%" id="dropdown-full">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</goa-form-item>
</div>

<div class="full-width">

<goa-form-item label="Basic dropdown">
  <goa-dropdown name="item" value="" (_change)="onChange($event)" width="50%" id="dropdown-half">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</goa-form-item>
</div>

<div class="full-width">
<goa-form-item label="Basic dropdown">
  <goa-dropdown name="item" value="" (_change)="onChange($event)" width="200px" id="dropdown-fix">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</goa-form-item>
</div>

// apps/react/src/bugs/Bug1319Page.tsx
import React from 'react';
import { GoADropdown, GoADropdownItem, GoAFormItem } from '@abgov/react-components';
import './Bug1319Page.css';

export default function Bug1307Page() {
  const onChange = (event) => {
    // handle change
    console.log(event.target.value);
  };

    return (
      <div className="full-width">
        <div className="form-item">
          <label>Basic dropdown</label>
          <GoADropdown name="item" value="" onChange={onChange} width="100%" id="dropdown-full">
            <GoADropdownItem value="red" label="Red" />
            <GoADropdownItem value="green" label="Green" />
            <GoADropdownItem value="blue" label="Blue" />
          </GoADropdown>
        </div>

        <div className="form-item">
          <label>Basic dropdown</label>
          <GoADropdown name="item" value="" onChange={onChange} width="50%" id="dropdown-half">
            <GoADropdownItem value="red" label="Red" />
            <GoADropdownItem value="green" label="Green" />
            <GoADropdownItem value="blue" label="Blue" />
          </GoADropdown>
        </div>

        <div className="form-item">
          <label>Basic dropdown</label>
          <GoADropdown name="item" value="" onChange={onChange} width="200px" id="dropdown-fix">
            <GoADropdownItem value="red" label="Red" />
            <GoADropdownItem value="green" label="Green" />
            <GoADropdownItem value="blue" label="Blue" />
          </GoADropdown>
        </div>
      </div>
    );
}
