// apps/angular/src/bugs/Bug1960Page/bug1960Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1960Page.component.html",
})
export class Bug1960PageComponent {


    initialValue = 2;

    onChange(event: Event) {
      this.initialValue = this.initialValue * 2
    }


}

<goa-form-item label="Basic dropdown">
  <goa-dropdown native name="item" value="" (_change)="onChange($event)" id="dropdown-on-change">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</goa-form-item>

<p id="on-change-initial-value">on change initial value is {{initialValue.toString()}}</p>

// apps/react/src/bugs/Bug1960Page.tsx
import React, { useState, useEffect } from 'react';
import { GoAFormItem, GoADropdown, GoADropdownItem } from '@abgov/react-components';

export default function Bug1960Page(props) {
  const [initialValue, setInitialValue] = useState(2);

  const handleChange = () => {
    setInitialValue(initialValue * 2);
  };
  return (
    <>
    <GoAFormItem label="Basic dropdown">
      <GoADropdown native name="item"  onChange={handleChange} id="dropdown-on-change">
        <GoADropdownItem value="red" label="Red"></GoADropdownItem>
        <GoADropdownItem value="green" label="Green"></GoADropdownItem>
        <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
      </GoADropdown>
    </GoAFormItem>

    <p id="on-change-initial-value">on change initial value is {initialValue.toString()}</p>

    </>
  )
}
