// apps/angular/src/bugs/Bug1307Page/bug1307Page.component.ts
import { Component } from "@angular/core";
import { FormControl } from "@angular/forms";

@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1307Page.component.html",
})
export class Bug1307PageComponent {
  onChange(event: Event) {
    // handle change
    console.log((event as CustomEvent).detail.value);
  }
}

<goa-form-item label="Basic dropdown">
  <goa-dropdown name="item" value="" (_change)="onChange($event)" id="dropdown">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</goa-form-item>

// apps/react/src/bugs/Bug1307Page.tsx
import React from 'react';
import { GoADropdown, GoADropdownItem, GoAFormItem } from '@abgov/react-components';

export default function Bug1307Page() {
  const onChange = (event) => {
    // handle change
    console.log(event.target.value);
  };

  return (
    <GoAFormItem label="Basic dropdown">
      <GoADropdown name="item" onChange={onChange} id="dropdown">
        <GoADropdownItem value="red" label="Red" />
        <GoADropdownItem value="green" label="Green" />
        <GoADropdownItem value="blue" label="Blue" />
      </GoADropdown>
    </GoAFormItem>
  );
}
