// apps/angular/src/bugs/Bug1577Page/bug1577Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1577Page.component.html",
})
export class Bug1577PageComponent {

}
<button id="button">focus anchor</button>
<goa-form-item label="Tuition">
  <goa-input  value="" name="tuition" leadingcontent="$" id="input">
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">ABCD</div>
  </goa-input>
</goa-form-item>
<hr />
<goa-form-item label="disabled">
  <goa-input  value="" name="disabled" leadingcontent="$" id="disabled" [disabled]=true>
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">ABCD</div>
  </goa-input>
</goa-form-item>
<hr />
<goa-form-item label="error">
  <goa-input  value="" name="error" leadingcontent="$" id="error" [error]=true>
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">ABCD</div>
  </goa-input>
</goa-form-item>

// apps/react/src/bugs/Bug1577Page.tsx
import React from "react";
import { GoAInput, GoAFormItem } from "@abgov/react-components";

export default function FormExample() {
  return (
    <div>
      {/* Focus Button */}
      <button id="button">focus anchor</button>

      {/* Tuition Input */}
      <GoAFormItem label="Tuition">
        <GoAInput value="" name="tuition" leadingContent="$" id="input">
          <div slot="leadingContent">$</div>
          <div slot="trailingContent">ABCD</div>
        </GoAInput>
      </GoAFormItem>

      <hr />

      {/* Disabled Input */}
      <GoAFormItem label="Disabled">
        <GoAInput
          value=""
          name="disabled"
          leadingContent="$"
          id="disabled"
          disabled={true} // Setting the input as disabled
        >
          <div slot="leadingContent">$</div>
          <div slot="trailingContent">ABCD</div>
        </GoAInput>
      </GoAFormItem>

      <hr />

      {/* Error Input */}
      <GoAFormItem label="Error">
        <GoAInput
          value=""
          name="error"
          leadingContent="$"
          id="error"
          error={true} // Showing error state
        >
          <div slot="leadingContent">$</div>
          <div slot="trailingContent">ABCD</div>
        </GoAInput>
      </GoAFormItem>
    </div>
  );
}
