// apps/angular/src/bugs/Bug1532Page/bug1532Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1532Page.component.html",
})
export class Bug1532PageComponent {
  value: any = "";
  onChange(event: any): void {
    this.value = event.target.value;
  }
}

<goa-form-item label="Basic">
  <goa-input type="number" width="20ch" name="item" [value]="value" (_change)="onChange($event)" id="input"></goa-input>
</goa-form-item>
<p id="input-value">For Value for input is {{ value }}</p>

// apps/react/src/bugs/Bug1532Page.tsx
import React, { useState } from "react";
import { GoAInput, GoAFormItem } from "@abgov/react-components";

export default function Bug1532Page() {
  const [value, setValue] = useState("");

  function onChange(name, value) {
    setValue(value);
  }

  return (
    <div>
      <GoAFormItem label="Basic">
        <GoAInput
          type="number"
          width="20ch"
          name="item"
          value={value}
          onChange={onChange}
          id="input"
        />
      </GoAFormItem>

      <p id="input-value">For Value for input is {value}</p>
    </div>
  );
}
