// apps/angular/src/bugs/Bug1380Page/bug1380Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1380Page.component.html",
})
export class Bug1380PageComponent {
  value: string = "2020-09-12";
  dateValue: Date = new Date('2020-12-03');
  onChange(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    this.value = inputElement.value;
  }

}

<goa-form-item label="value">
  <goa-input type="date" width="20ch" name="item" [value]="value" (_change)="onChange($event)" id="input-string"></goa-input>
</goa-form-item>
<hr />
<goa-form-item label="dateValue">
  <goa-input type="date" width="20ch" name="item" [value]="dateValue" id="input-date"></goa-input>
</goa-form-item>
<p id="input-value">For Value for input is {{ value }}</p>

// apps/react/src/bugs/Bug1380Page.tsx
import React, { useState } from "react";
import { GoAInput, GoAFormItem } from "@abgov/react-components";

export default function Bug1380Page() {
  // Initial state for string value and date value
  const [value, setValue] = useState("2020-09-12");
  const [dateValue, setDateValue] = useState(new Date("2020-12-03"));

  // Correct onChange function
  function onChange(name: string, date: string) {
    setValue(date);
  }

  return (
    <div>
      {/* Input with string value */}
      <GoAFormItem label="value">
        <GoAInput
          type="date"
          width="20ch"
          name="item"
          value={value}
          onChange={onChange}
          id="input-string"
        />
      </GoAFormItem>

      <hr />

      {/* Input with Date object value */}
      <GoAFormItem label="dateValue">
        <GoAInput
          type="date"
          width="20ch"
          name="item"
          value={dateValue}
          id="input-date"
        />
      </GoAFormItem>

      <p id="input-value">For Value for input is {value}</p>
    </div>
  );
}
