// apps/angular/src/bugs/Bug1244Page/bug1244Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1244Page.component.html",
})
export class Bug1244PageComponent {
  ngOnInit(): void {
    //console.error('This is an error message:');
  }
}

<goa-form-item label="Basic dropdown">
  <goa-dropdown name="item" value="" [native]=true id="dropdown-target">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</goa-form-item>

// apps/react/src/bugs/Bug1244Page.tsx
import React, { useState, useEffect } from 'react';
import { GoAFormItem, GoADropdown, GoADropdownItem } from "@abgov/react-components";

export default function Bug1244Page(props) {
  return (
    <>
    <GoAFormItem label="Basic dropdown">
      <GoADropdown name="item" value="" native={true} id="dropdown-target">
        <GoADropdownItem value="red" label="Red"></GoADropdownItem>
        <GoADropdownItem value="green" label="Green"></GoADropdownItem>
        <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
      </GoADropdown>
    </GoAFormItem>
    </>
  )
}
