// apps/angular/src/bugs/Bug1237Page/bug1237Page.component.ts
import { Component } from "@angular/core";
import { FormControl } from '@angular/forms';

@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1237Page.component.html",
})
export class Bug1237PageComponent {
  public options = [
    { value: '', label: '' },
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  public formControl = new FormControl<string | null>(null);
  public formControlNative = new FormControl<string | null>(null);
  public formControlNonNative = new FormControl<string | null>(null);


  constructor() {}

  ngOnInit(): void {
    this.formControl.valueChanges.subscribe((value) => {
      console.log(`formControl Received value: ${value}`);
      if (!value) {
        return;
      }
    });
    this.formControlNative.valueChanges.subscribe((value) => {
      console.log(`formControlNative Received value: ${value}`);
      if (!value) {
        return;
      }
    });
    this.formControlNonNative.valueChanges.subscribe((value) => {
      console.log(`formControlNonNative Received value: ${value}`);
      if (!value) {
        return;
      }
    });
  }
}

<goa-container>
  <p> When Enter Key is pressed, option is selected, and dropdown is closed</p>
</goa-container>


<goa-container>

  <goa-form-item label="Dropdown Native">
    <goa-dropdown
      goaValue
      native
      [formControl]="formControlNative"
      [value]="formControlNative.value"
      id="dropdown-native"
    >
      <goa-dropdown-item
        *ngFor="let opt of options"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>
  </goa-form-item>

  <goa-form-item label="ropdown Non Native">
    <goa-dropdown
      goaValue
      [formControl]="formControlNonNative"
      [value]="formControlNonNative.value"
      id="dropdown-non-native"
      name='dropdown-non-native'
    >
      <goa-dropdown-item
        *ngFor="let opt of options"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>
  </goa-form-item>

  <goa-form-item label="Select">


  <select [formControl]="formControl" [value]="formControl.value" id="select">
    <option *ngFor="let opt of options" [value]="opt.value">
      {{ opt.label }}
    </option>
  </select>
</goa-form-item>

</goa-container>

// apps/react/src/bugs/Bug1237Page.tsx
import React, { useState, useEffect } from 'react';
import { GoAContainer, GoAIconButton, GoADropdown, GoADropdownItem, GoAFormItem } from '@abgov/react-components';

export default function Bug1237Page(props) {

  const options = [
    { value: '', label: '' },
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];


  const [formControlNative, setFormControlNative] = useState<string | null>('');
  const [formControlNonNative, setFormControlNonNative] = useState<string | null>('');
  const [formControl, setFormControl] = useState<string | null>('');


  const resetFormControl = () => setFormControl('');
  const resetFormControlNative = () => setFormControlNative('');
  const resetFormControlNonNative = () => setFormControlNonNative('');


  function onChange(name, value) {
    setFormControl(value)
  }

  function onChangeNative(name, value) {
    setFormControlNative(value)
  }

  function onChangelNonNative(name, value) {
    setFormControlNonNative(value)
  }


  return (
    <>
    <GoAContainer>
      <p> When Enter Key is pressed, option is selected, and dropdown is closed</p>
    </GoAContainer>


    <GoAContainer>

      <GoAFormItem label="Dropdown Native">
        <GoADropdown
          value={formControlNative}
          onChange={onChangeNative}
          native={true}
          id="dropdown-native"
        >
          {options.map((opt, index) => (
            <GoADropdownItem
              key={index}
              value={opt.value}
              label={opt.label}
            />
          ))}
        </GoADropdown>
      </GoAFormItem>

      <GoAFormItem label="Dropdown Non Native">
        <GoADropdown
          value={formControlNonNative}
          onChange={onChangelNonNative}
          id="dropdown-non-native"
          name='dropdown-non-native'
        >
        {options.map((opt, index) => (
          <GoADropdownItem
            key={index}
            value={opt.value}
            label={opt.label}
          />
        ))}

        </GoADropdown>
      </GoAFormItem>

      <GoAFormItem label="Select">


      <select   value={formControlNative}  onChange={onChange} id="select">
        {options.map((opt, index) => (
          <option key={index} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    </GoAFormItem>

    </GoAContainer>

    </>
  )
}
