// apps/angular/src/bugs/Bug1867Page/bug1867Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1867Page.component.html",
})
export class Bug1867PageComponent {
  onClick(event: Event) {
    console.log("onClick")
  }
  onChange(event: Event) {
    console.log("onChange")
  }
}

<goa-block gap="xl" direction="column">
  <goa-form-item label="Street Address">
    <goa-input name="full" type="text" value="" (_change)="onChange($event)" width="100%"></goa-input>
  </goa-form-item>
  <goa-form-item label="Suite or unit #">
    <goa-input name="half" type="text" value="" (_change)="onChange($event)" width="50%"></goa-input>
  </goa-form-item>
  <goa-form-item label="City/town">
    <goa-input name="fix" type="text" value="" (_change)="onChange($event)" width="260px"></goa-input>
  </goa-form-item>
  <goa-block direction="row">
    <goa-form-item label="Provice/territory">
      <goa-dropdown (_change)="onChange($event)" name="province" value="alberta">
        <goa-dropdown-item label="Alberta" value="alberta"></goa-dropdown-item>
        <goa-dropdown-item label="BC" value="bc"></goa-dropdown-item>
        <goa-dropdown-item label="Manitoba" value="manitoba"></goa-dropdown-item>
        <goa-dropdown-item label="New Brunswick" value="new-brunswick"></goa-dropdown-item>
        <goa-dropdown-item label="Newfoundland and Labrador" value="newfoundland"></goa-dropdown-item>
        <goa-dropdown-item label="Nova Scotia" value="nova-scotia"></goa-dropdown-item>
        <goa-dropdown-item label="Ontario" value="ontario"></goa-dropdown-item>
        <goa-dropdown-item label="Prince Edward Island" value="prince-edward-island"></goa-dropdown-item>
        <goa-dropdown-item label="Quebec" value="quebec"></goa-dropdown-item>
        <goa-dropdown-item label="Saskatchewan" value="saskatchewan"></goa-dropdown-item>
      </goa-dropdown>
    </goa-form-item>
    <goa-form-item label="Postal Code">
      <goa-input name="postalCode" type="text" value="" (_change)="onChange($event)" width="100%"></goa-input>
    </goa-form-item>
  </goa-block>
</goa-block>
<goa-button-group alignment="start" mt="2xl">
  <goa-button type="primary" (_click)="onClick($event)">
    Submit and continue
  </goa-button>
  <goa-button type="secondary" (_click)="onClick($event)">
    Cancel
  </goa-button>
</goa-button-group>

// apps/react/src/bugs/Bug1867Page.tsx
import React from "react";
import { GoAInput, GoADropdown, GoADropdownItem, GoAButton  } from "@abgov/react-components";

export default function Bug1867Page(props) {

  const onClick = (event: React.MouseEvent) => {
    console.log("onClick");
  };

  const onChange = (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    console.log("onChange");
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
      <div className="form-item">
        <label>Street Address</label>
        <GoAInput name="full" type="text" onChange={onChange} width="100%" />
      </div>

      <div className="form-item">
        <label>Suite or unit #</label>
        <GoAInput name="half" type="text" onChange={onChange} width="50%" />
      </div>

      <div className="form-item">
        <label>City/town</label>
        <GoAInput name="fix" type="text" onChange={onChange} width="260px" />
      </div>

      <div style={{ display: "flex", flexDirection: "row" }}>
        <div className="form-item">
          <label>Province/territory</label>
          <GoADropdown name="province" defaultValue="alberta" onChange={onChange}>
            <GoADropdownItem label="Alberta" value="alberta" />
            <GoADropdownItem label="BC" value="bc" />
            <GoADropdownItem label="Manitoba" value="manitoba" />
            <GoADropdownItem label="New Brunswick" value="new-brunswick" />
            <GoADropdownItem label="Newfoundland and Labrador" value="newfoundland" />
            <GoADropdownItem label="Nova Scotia" value="nova-scotia" />
            <GoADropdownItem label="Ontario" value="ontario" />
            <GoADropdownItem label="Prince Edward Island" value="prince-edward-island" />
            <GoADropdownItem label="Quebec" value="quebec" />
            <GoADropdownItem label="Saskatchewan" value="saskatchewan" />
          </GoADropdown>
        </div>

        <div className="form-item">
          <label>Postal Code</label>
          <GoAInput name="postalCode" type="text" onChange={onChange} width="100%" />
        </div>
      </div>

      <div style={{ marginTop: "32px", display: "flex", alignItems: "flex-start" }}>
        <GoAButton type="primary" onClick={onClick}>Submit and continue</GoAButton>
        <GoAButton type="secondary" onClick={onClick}>Cancel</GoAButton>
      </div>
    </div>
  );
};
