// apps/angular/src/bugs/Bug1698Page/bug1698Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1698Page.component.html",
  styleUrls: ['./bug1698Page.component.css'],

})
export class Bug1698PageComponent {

}

<!-- HTML content for bug1698Page.component.html -->

<div class="container">
  <goa-dropdown name="item" value="" width="100%" id="dropdown-full">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</div>
<div class="container">
  <goa-dropdown name="item" value="" width="50%" id="dropdown-half">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</div>
<div class="container">
  <goa-dropdown name="item" value="" width="25%" id="dropdown-quarter">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
</div>

// apps/react/src/bugs/Bug1698Page.tsx
import React from 'react';
import { GoADropdown, GoADropdownItem } from '@abgov/react-components';
import './Bug1698Page.css';

const Bug1698Page = () => {
  return (
    <div>
    <div className="container">
      <GoADropdown name="item" value="" width="100%" id="dropdown-full">
        <GoADropdownItem value="red" label="Red" />
        <GoADropdownItem value="green" label="Green" />
        <GoADropdownItem value="blue" label="Blue" />
      </GoADropdown>
    </div>
    <div className="container">
      <GoADropdown name="item" value="" width="50%" id="dropdown-half">
        <GoADropdownItem value="red" label="Red" />
        <GoADropdownItem value="green" label="Green" />
        <GoADropdownItem value="blue" label="Blue" />
      </GoADropdown>
    </div>
    <div className="container">
      <GoADropdown name="item" value="" width="25%" id="dropdown-quarter">
        <GoADropdownItem value="red" label="Red" />
        <GoADropdownItem value="green" label="Green" />
        <GoADropdownItem value="blue" label="Blue" />
      </GoADropdown>
    </div>
</div>
  );
};

export default Bug1698Page;
