// apps/angular/src/bugs/Bug2033Page/bug2033Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug2033Page.component.html",
})
export class Bug2033PageComponent {
  step = -1;
  status = ["incomplete", "incomplete", "incomplete", "incomplete"];

  updateStep(event: Event) {
    this.step = (event as CustomEvent).detail.step;
  }

  setPage(page: number) {
    if (page < 1 || page > 4) return;
    this.step = page;
  }
}

<span>Current step {{step}}</span>
<goa-form-stepper ml="s" mr="s" [step]="step" (_change)="updateStep($event)">
  <goa-form-step text="Personal details" [status]="status[0]"></goa-form-step>
  <goa-form-step text="Employment history" [status]="status[1]"></goa-form-step>
  <goa-form-step text="References" [status]="status[2]"></goa-form-step>
  <goa-form-step text="Review" [status]="status[3]"></goa-form-step>
</goa-form-stepper>
<goa-pages [current]="step">
  <div>Page 1 content with status: {{status[0]}}</div>
  <div>Page 2 content with status: {{status[1]}}</div>
  <div>
    Page 3 content with current status: {{status[2]}}
  </div>
  <div>
    Page 4 content with current status: {{status[3]}}
  </div>
</goa-pages>
<div style="display: flex; justify-content: space-between">
  <goa-button (_click)="setPage(step - 1)" type="secondary"
  >Previous</goa-button
  >
  <goa-button (_click)="setPage(step + 1)" type="primary">Next</goa-button>
</div>

// apps/react/src/bugs/Bug2033Page.tsx
import React, { useState } from 'react';
import { GoAFormStepper, GoAFormStep, GoAFormStepStatusType, GoAPages, GoAButton } from "@abgov/react-components";

export default function Bug2033Page() {
  const [step, setStep] = useState(-1);
  const [status, setStatus] = useState<GoAFormStepStatusType[]>(["incomplete", "incomplete", "incomplete", "incomplete"]);

  return (
    <>
      <span>Current step {step}</span>
      <GoAFormStepper ml="s" mr="s" step={ step } onChange={ setStep }>
        <GoAFormStep text="Personal details" status={ status[0] }></GoAFormStep>
        <GoAFormStep text="Employment history" status={ status[1] }></GoAFormStep>
        <GoAFormStep text="References" status={ status[2] }></GoAFormStep>
        <GoAFormStep text="Review" status={ status[3] }></GoAFormStep>
      </GoAFormStepper>
      <GoAPages current={ step }>
        <div>Page 1 content with status: { status[0] }</div>
        <div>Page 2 content with status: { status[1] }</div>
        <div>
          Page 3 content with current status: { status[2] }
        </div>
        <div>
          Page 4 content with current status: { status[3] }
        </div>
      </GoAPages>
      <div style={{ display: "flex", justifyContent: "space-between" }}>
        <GoAButton onClick={ () => setStep(step - 1) } type="secondary">Previous</GoAButton>
        <GoAButton onClick={ () => setStep(step + 1) } type="primary">Next</GoAButton>
      </div>
    </>
  )
}
