// apps/angular/src/bugs/Bug976Page/bug976Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug976Page.component.html",
})
export class Bug976PageComponent {

}
<goa-form-item label="Tuition">
  <goa-input  value="" name="tuition" id="input" disabled={true} >
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">ABCD</div>
  </goa-input>
</goa-form-item>

// apps/react/src/bugs/Bug976Page.tsx


import React, { useState, useEffect } from 'react';
import { GoAInput, GoAFormItem } from "@abgov/react-components";

export default function Bug976Page(props) {



  return (
    <div>
      <GoAFormItem label="Tuition">
        <GoAInput
          name="tuition"
          leadingContent="$"
          trailingContent="ABCDE"
          id="input"
disabled={true}
        >
        </GoAInput>
      </GoAFormItem>
    </div>
  );
}
