// apps/react/src/bugs/Bug1289Page.tsx
import React, { useState } from 'react';
import { GoADropdown, GoADropdownItem } from '@abgov/react-components';
import './Bug1289Page.css'; // Assuming you named the CSS file as such

export default function Bug1289Page() {
  const [selected, setSelected] = useState('');

  const options = [
    { value: '', label: '' },
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  const onChange = (event) => {
    setSelected(event.target.value);
  };

  return (
    <div className="absolute-container">
      <GoADropdown
        name="item"
        value={selected}
        onChange={onChange}
        id="dropdown"
        relative={true}
      >
        {options.map((opt, index) => (
          <GoADropdownItem
            key={index}
            value={opt.value}
            label={opt.label}
          />
        ))}
      </GoADropdown>
    </div>
  );
}

// apps/angular/src/bugs/Bug1289Page/bug1289Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1289Page.component.html",
  styleUrls: ['./bug1289Page.component.css'],
})
export class Bug1289PageComponent {
  public selected: string | null = null;

  public options = [
    { value: '', label: '' },
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  onChange(event: any): void {
    this.selected = event.target.value;
  }
}

  <div class="absolute-container ">
    <goa-dropdown name="item" value="" (_change)="onChange($event)" id="dropdown" relative=true>
      <goa-dropdown-item
        *ngFor="let opt of options"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>
  </div>
