// apps/react/src/bugs/Bug1796Page.tsx
import React from "react";
import { GoAInput, GoAFormItem } from "@abgov/react-components";

export default function Bug1796Page() {
  const onClick = (event: React.MouseEvent) => {
    console.log("onClick");
  };

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    console.log("onChange");
  };

  return (
    <div>
      {/* Regular Label */}
      <div id="regular-label">
        <GoAFormItem label="Basic" labelSize="regular">
          <GoAInput name="item" width="20ch" onChange={onChange} />
        </GoAFormItem>
      </div>
      <hr />

      {/* Regular Label with Help Text */}
      <div id="regular-label-help">
        <GoAFormItem label="Basic" labelSize="regular" helpText="Help Text">
          <GoAInput name="item" width="20ch" onChange={onChange} />
        </GoAFormItem>
      </div>
      <hr />

      {/* Regular Label with Help and Error Text */}
      <div id="regular-label-help-error">
        <GoAFormItem
          label="Basic"
          labelSize="regular"
          helpText="Help Text"
          error="Error Text"
        >
          <GoAInput name="item" width="20ch" onChange={onChange} />
        </GoAFormItem>
      </div>
      <hr />

      {/* Large Label */}
      <div id="large-label">
        <GoAFormItem label="Basic" labelSize="large">
          <GoAInput name="item" width="20ch" onChange={onChange} />
        </GoAFormItem>
      </div>
      <hr />

      {/* Large Label with Help Text */}
      <div id="large-label-help">
        <GoAFormItem label="Basic" labelSize="large" helpText="Help Text">
          <GoAInput name="item" width="20ch" onChange={onChange} />
        </GoAFormItem>
      </div>
      <hr />

      {/* Large Label with Help and Error Text */}
      <div id="large-label-help-error">
        <GoAFormItem
          label="Basic"
          labelSize="large"
          helpText="Help Text"
          error="Error Text"
        >
          <GoAInput name="item" width="20ch" onChange={onChange} />
        </GoAFormItem>
      </div>
    </div>
  );
}

// apps/angular/src/bugs/Bug1796Page/bug1796Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1796Page.component.html",
})
export class Bug1796PageComponent {
  onClick(event: Event) {
    console.log("onClick")
  }
  onChange(event: Event) {
    console.log("onChange")
  }
}

<div id="regular-label">
<goa-form-item label="Basic" labelsize="regular">
  <goa-input name="item" width="20ch" (_change)="onChange($event)"></goa-input>
</goa-form-item>
</div>
<hr />
<div id="regular-label-help">
<goa-form-item label="Basic" labelsize="regular" helptext="Help Text">
  <goa-input name="item" width="20ch" (_change)="onChange($event)"></goa-input>
</goa-form-item>
</div>
<hr />

<div id="regular-label-help-error">
<goa-form-item label="Basic" labelsize="regular" helptext="Help Text" error="Error Text">
  <goa-input name="item" width="20ch" (_change)="onChange($event)"></goa-input>
</goa-form-item>
</div>

<hr />






<div id="large-label">
<goa-form-item label="Basic" labelsize="large">
  <goa-input name="item" width="20ch" (_change)="onChange($event)"></goa-input>
</goa-form-item>
</div>
<hr />

<div id="large-label-help">
<goa-form-item label="Basic" labelsize="large" helptext="Help Text">
  <goa-input name="item" width="20ch" (_change)="onChange($event)"></goa-input>
</goa-form-item>
</div>
<hr />

<div id="large-label-help-error">
<goa-form-item label="Basic" labelsize="large" helptext="Help Text" error="Error Text">
  <goa-input name="item" width="20ch" (_change)="onChange($event)"></goa-input>
</goa-form-item>
</div>
