// apps/react/src/bugs/Bug1494Page.tsx
import React from 'react';
import { GoATabs, GoATab, GoADropdown, GoADropdownItem, GoAFormItem } from '@abgov/react-components';

const Bug1494Page = () => {
  const onChange = (event) => {
    // handle change
    console.log("abc");
  };


  return (
    <GoATabs>
      <GoATab heading="Tab Item 1">
        <GoAFormItem label="dropdown-one">
          <GoADropdown name="item-one" value="" id="dropdown-one" filterable testid="dropdown-one-input" onChange={onChange} >
            <GoADropdownItem value="red" label="Red" />
            <GoADropdownItem value="green" label="Green" />
            <GoADropdownItem value="blue" label="Blue" />
            <GoADropdownItem value="black" label="Black" />
            <GoADropdownItem value="blonde" label="Blonde" />
          </GoADropdown>
        </GoAFormItem>
        <br />
        <br />
        <br />
        <GoAFormItem label="dropdown-two">
          <GoADropdown name="item-two" value="" id="dropdown-two" onChange={onChange} >
            <GoADropdownItem value="red" label="Red" />
            <GoADropdownItem value="green" label="Green" />
            <GoADropdownItem value="blue" label="Blue" />
          </GoADropdown>
        </GoAFormItem>
      </GoATab>
      <GoATab heading="Tab Item 2">
        Tab Item 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      </GoATab>
      <GoATab heading="Tab Item 3">
        Tab Item 3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      </GoATab>
    </GoATabs>
  );
};

export default Bug1494Page;

// apps/angular/src/bugs/Bug1494Page/bug1494Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1494Page.component.html",
})
export class Bug1494PageComponent {

}
<!-- HTML content for bug1494Page.component.html -->




<goa-tabs>
  <goa-tab heading="Tab Item 1">
    <goa-form-item label="dropdown-one">
      <goa-dropdown name="item-one" value="" id="dropdown-one" [filterable]=true testid="dropdown-one-input">
        <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
        <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
        <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
        <goa-dropdown-item value="black" label="Black"></goa-dropdown-item>
        <goa-dropdown-item value="blonde" label="Blonde"></goa-dropdown-item>
      </goa-dropdown>
    </goa-form-item>
    <br />
    <br />
    <br />
    <goa-form-item label="dropdown-two">
      <goa-dropdown name="item-two" value="" id="dropdown-two">
        <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
        <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
        <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
      </goa-dropdown>
    </goa-form-item>
  </goa-tab>
  <goa-tab heading="Tab Item 2">
    Tab Item 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  </goa-tab>
  <goa-tab heading="Tab Item 3">
    Tab Item 3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  </goa-tab>
</goa-tabs>
