// apps/react/src/bugs/Bug1734Page.tsx
import React, { useState, useEffect } from 'react';
import { GoADropdown, GoADropdownItem } from "@abgov/react-components";
import './Bug1734Page.css';

export default function Bug1734Page(props) {
  return (
    <>
    <div class="full-height-minus-40px">SPACE TAKER</div>
    <GoADropdown name="item" value="" id="dropdown">
        <GoADropdownItem value="red" label="Red"></GoADropdownItem>
        <GoADropdownItem value="green" label="Green"></GoADropdownItem>
        <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
      </GoADropdown>

    </>
  )
}

// apps/angular/src/bugs/Bug1734Page/bug1734Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1734Page.component.html",
  styleUrls: ['./bug1734Page.component.css'],

})
export class Bug1734PageComponent {

}

<div class="full-height-minus-40px">SPACE TAKER</div>
<goa-dropdown name="item" value="" id="dropdown">
    <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
    <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
    <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
  </goa-dropdown>
