// apps/react/src/bugs/Bug1308Page.tsx
import React, { useState, useEffect } from 'react';
import { GoAInput, GoAFormItem } from "@abgov/react-components";

export default function Bug1308Page(props) {


  return (
    <div>
      <GoAFormItem label="Tuition">
        <GoAInput
          value={value}
          name="tuition"
          leadingContent="$"
          trailingContent="ABCDE"
          id="input"
        >
        </GoAInput>
      </GoAFormItem>
    </div>
  );
}

// apps/angular/src/bugs/Bug1308Page/bug1308Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1308Page.component.html",
})
export class Bug1308PageComponent {

}
<goa-form-item label="Tuition">
  <goa-input  value="" name="tuition" leadingcontent="$" id="input">
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">ABCD</div>
  </goa-input>
</goa-form-item>
