// apps/react/src/bugs/Bug1142Page.tsx
import React, { useEffect, useState } from 'react';
import { GoAContainer, GoAGrid, GoAFormItem, GoADropdown, GoADropdownItem, GoAButton } from '@abgov/react-components';

const Bug1142PageComponent: React.FC = () => {
  const optionsEmpty = [
    { value: '', label: '' },
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  const optionsNull = [
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  const [formControlEmptyNative, setFormControlEmptyNative] = useState<string | null>('');
  const [formControlEmptyNonNative, setFormControlEmptyNonNative] = useState<string | null>('');
  const [formControlNullNative, setFormControlNullNative] = useState<string | null>('');
  const [formControlNullNonNative, setFormControlNullNonNative] = useState<string | null>('');
  const [formControlNative, setFormControlNative] = useState<string | null>('');


  const resetFormControlEmptyNative = () => setFormControlEmptyNative('');
  const resetFormControlEmptyNonNative = () => setFormControlEmptyNonNative('');
  const resetFormControlNullNative = () => setFormControlNullNative('');
  const resetFormControlNullNonNative = () => setFormControlNullNonNative('');
  const resetFormControlNative = () => setFormControlNative('');


  function onChangeEmptyNative(name, value) {
    setFormControlEmptyNative(value)
  }

  function onChangeEmptyNonNative(name, value) {
    setFormControlEmptyNonNative(value)
  }

  function onChangeNullNative(name, value) {
    setFormControlNullNative(value)
  }

  function onChangeNullNonNative(name, value) {
    setFormControlNullNonNative(value)
  }

  return (
    <>
      <div>For this issue, there are 4 cases:</div>
      <ul>
        <li>1 - GoADropdown is native and has an option of ''</li>
        <li>2 - GoADropdown is not native and has an option of ''</li>
        <li>3 - GoADropdown is native and does not have an option of ''</li>
        <li>4 - GoADropdown is not native and does not have an option of ''</li>
      </ul>
      <div>For all 4 cases, when reset is clicked, the dropdown should display an option of ''</div>

      <GoAContainer>
        <GoAGrid>
          <GoAFormItem label="Dropdown Native With Empty String Value">
            <GoADropdown
              value={formControlEmptyNative}
              onChange={onChangeEmptyNative}
              id="dropdown-empty-native"
              native
            >
              <GoADropdownItem value="" label=""></GoADropdownItem>
              <GoADropdownItem value="opt1" label="Option 1"></GoADropdownItem>
              <GoADropdownItem value="opt2" label="Option 2"></GoADropdownItem>
              <GoADropdownItem value="opt3" label="Option 3"></GoADropdownItem>
              <GoADropdownItem value="opt4" label="Option 4"></GoADropdownItem>
            </GoADropdown>
          </GoAFormItem>
          <GoAButton testId="dropdown-empty-native-reset-button-shadow" id="dropdown-empty-native-reset-button">Reset</GoAButton>
        </GoAGrid>
      </GoAContainer>

      <GoAContainer>
        <GoAGrid>
          <GoAFormItem label="Dropdown Not Native With Empty String Value">
            <GoADropdown
              value={formControlEmptyNonNative}
              onChange={onChangeEmptyNonNative}
              id="dropdown-empty-non-native"

            >
            <GoADropdownItem value="" label=""></GoADropdownItem>
            <GoADropdownItem value="opt1" label="Option 1"></GoADropdownItem>
            <GoADropdownItem value="opt2" label="Option 2"></GoADropdownItem>
            <GoADropdownItem value="opt3" label="Option 3"></GoADropdownItem>
            <GoADropdownItem value="opt4" label="Option 4"></GoADropdownItem>
            </GoADropdown>
          </GoAFormItem>
          <GoAButton  testId="dropdown-empty-non-native-reset-button-shadow" id="dropdown-empty-non-native-reset-button"  onClick={resetFormControlEmptyNonNative}>Reset</GoAButton>
        </GoAGrid>
      </GoAContainer>

      <GoAContainer>
        <GoAGrid>
          <GoAFormItem label="Dropdown Native Without Empty String Value">
            <GoADropdown
              value={formControlNullNative}
              onChange={onChangeNullNative}
              id="dropdown-null-native"

              native
            >
            <GoADropdownItem value="opt1" label="Option 1"></GoADropdownItem>
            <GoADropdownItem value="opt2" label="Option 2"></GoADropdownItem>
            <GoADropdownItem value="opt3" label="Option 3"></GoADropdownItem>
            <GoADropdownItem value="opt4" label="Option 4"></GoADropdownItem>
            </GoADropdown>
          </GoAFormItem>
          <GoAButton onClick={resetFormControlNullNative}  testId="dropdown-null-native-reset-button-shadow" id="dropdown-null-native-reset-button" >Reset</GoAButton>
        </GoAGrid>
      </GoAContainer>

      <GoAContainer>
        <GoAGrid>
          <GoAFormItem label="Dropdown Not Native Without Empty String Value">
            <GoADropdown
              value={formControlNullNonNative}
              onChange={onChangeNullNonNative}
              id="dropdown-null-non-native"

            >
            <GoADropdownItem value="opt1" label="Option 1"></GoADropdownItem>
            <GoADropdownItem value="opt2" label="Option 2"></GoADropdownItem>
            <GoADropdownItem value="opt3" label="Option 3"></GoADropdownItem>
            <GoADropdownItem value="opt4" label="Option 4"></GoADropdownItem>
            </GoADropdown>
          </GoAFormItem>
          <GoAButton onClick={resetFormControlNullNonNative} testId="dropdown-null-non-native-reset-button-shadow" id="dropdown-null-non-native-reset-button" >Reset</GoAButton>
        </GoAGrid>
      </GoAContainer>

      <GoAContainer>
        <GoAGrid>
          <div>
            <h2>Native Select</h2>
            <select >
              <option value="opt1">Option 1</option>
              <option value="opt2">Option 2</option>
              <option value="opt3">Option 3</option>
              <option value="opt4">Option 4</option>
            </select>
          </div>
          <GoAButton onClick={resetFormControlNative}>Reset</GoAButton>
        </GoAGrid>
      </GoAContainer>
    </>
  );
};

export default Bug1142PageComponent;

// apps/angular/src/bugs/Bug1142Page/bug1142Page.component.ts
import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1142Page.component.html",
})
export class Bug1142PageComponent {

}
<goa-container>
  <p> For this issue, there are 4 cases </p>
  <p> 1 - goa-dropdown is native and have an option of '' </p>
  <p> 2 - goa-dropdown is not native and have an option of '' </p>
  <p> 3 - goa-dropdown is native and do not have an option of '' </p>
  <p> 4 - goa-dropdown is not native and do not have an option of '' </p>
  <p> For All 4 cases when reset is clicked, the dropdown should display an option of '' </p>
</goa-container>

<goa-container><goa-grid>


  <goa-form-item label="Dropdown Native With Empty String Value">
    <goa-dropdown
      goaValue
      native
      [formControl]="formControlEmptyNative"
      [value]="formControlEmptyNative.value"
      id="dropdown-empty-native"
    >
      <goa-dropdown-item
        *ngFor="let opt of optionsEmpty"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>
  </goa-form-item>
  <goa-button testid="dropdown-empty-native-reset-button-shadow" id="dropdown-empty-native-reset-button" (_click)="formControlEmptyNativeReset()">Reset</goa-button>

</goa-grid></goa-container>

<goa-container><goa-grid>

  <goa-form-item label="Dropdown Not Native With Empty String Value">
    <goa-dropdown
      goaValue
      [formControl]="formControlEmptyNonNative"
      [value]="formControlEmptyNonNative.value"
      id="dropdown-empty-non-native"
    >
      <goa-dropdown-item
        *ngFor="let opt of optionsEmpty"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>
  </goa-form-item>
  <goa-button testid="dropdown-empty-non-native-reset-button-shadow" id="dropdown-empty-non-native-reset-button" (_click)="formControlEmptyNonNativeReset()">Reset</goa-button>

</goa-grid></goa-container>

<goa-container><goa-grid>

  <goa-form-item label="Dropdown Native Without Empty String Value">
    <goa-dropdown
      goaValue
      native
      [formControl]="formControlNullNative"
      [value]="formControlNullNative.value"
      id="dropdown-null-native"
    >
      <goa-dropdown-item
        *ngFor="let opt of optionsNull"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>
  </goa-form-item>
  <goa-button testid="dropdown-null-native-reset-button-shadow" id="dropdown-null-native-reset-button" (_click)="formControlNullNativeReset()">Reset</goa-button>

</goa-grid></goa-container>

<goa-container><goa-grid>

  <goa-form-item label="Dropdown Non Native Without Empty String Value">
    <goa-dropdown
      goaValue
      [formControl]="formControlNullNonNative"
      [value]="formControlNullNonNative.value"
      id="dropdown-null-non-native"
    >
      <goa-dropdown-item
        *ngFor="let opt of optionsNull"
        [value]="opt.value"
        [label]="opt.label"
      ></goa-dropdown-item>
    </goa-dropdown>


  </goa-form-item>

  <goa-button testid="dropdown-null-non-native-reset-button-shadow" id="dropdown-null-non-native-reset-button" (_click)="formControlNullNonNativeReset()">Reset</goa-button>

</goa-grid></goa-container>

<goa-container><goa-grid>
  <div>
    <h2>Native Select</h2>
    <select [formControl]="formControlNative" [value]="formControlNative.value">
      <option *ngFor="let opt of optionsNull" [value]="opt.value">
        {{ opt.label }}
      </option>
    </select>
  </div>
  <goa-button testid="reset-button-shadow" id="reset-button" (_click)="formControlNativeReset()">Reset</goa-button>

</goa-grid>
</goa-container>
