// apps/react/src/bugs/Bug1378Page.tsx
import React, { useState, useEffect } from 'react';
import { GoADropdown, GoADropdownItem, GoAFormItem } from '@abgov/react-components';

const Bug1378Page = () => {

  const options = [
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  const [onChangeInitialValue, setOnChangeInitialValue] = useState(2);


  const handleChange = (event) => {
    setOnChangeInitialValue(onChangeInitialValue * 2);
  };


  return (
    <div>
      <GoAFormItem label="On Change Function">
        <GoADropdown
          name="onChange"
          value=""
          onChange={handleChange}
          id="dropdown-on-change"
        >
          {options.map(opt => (
            <GoADropdownItem key={opt.value} value={opt.value} label={opt.label} />
          ))}
        </GoADropdown>
      </GoAFormItem>

      <p id="on-change-initial-value">
        on change initial value is {onChangeInitialValue.toString()}
      </p>

    </div>
  );
};

export default Bug1378Page;

// apps/angular/src/bugs/Bug1378Page/bug1378Page.component.ts
import { Component } from "@angular/core";
import { FormControl } from '@angular/forms';

@Component({
  selector: "abgov-styles",
  templateUrl: "./bug1378Page.component.html",
})
export class Bug1378PageComponent {

  public options = [
    { value: 'opt1', label: 'Option 1' },
    { value: 'opt2', label: 'Option 2' },
    { value: 'opt3', label: 'Option 3' },
    { value: 'opt4', label: 'Option 4' },
  ];

  onChangeInitialValue = 2;
  formControlInitialValue = 3;

  onChange(event: Event) {
    this.onChangeInitialValue = this.onChangeInitialValue * 2
  }

  public formControl = new FormControl<string | null>(null);

  ngOnInit() {
    this.formControl.valueChanges.subscribe((value) => {
      this.formControlInitialValue = this.formControlInitialValue * 2
    })
  }


}

<goa-form-item label="On Change Function">
  <goa-dropdown name="onChange" value="" (_change)="onChange($event)" id="dropdown-on-change">
    <goa-dropdown-item *ngFor="let opt of options"
      [value]="opt.value"
      [label]="opt.label"
    ></goa-dropdown-item>
  </goa-dropdown>

</goa-form-item>

<goa-form-item label="On Change Function">

<goa-dropdown goaValue [formControl]="formControl" id="dropdown-form-control">
  <goa-dropdown-item *ngFor="let opt of options"
    [value]="opt.value"
    [label]="opt.label"
  ></goa-dropdown-item>
</goa-dropdown>
</goa-form-item>

<p id="on-change-initial-value">on change initial value is {{onChangeInitialValue.toString()}}</p>
<p id="form-control-initial-value">form control initial value is {{formControlInitialValue.toString()}}</p>
